### ISSUE TITLE
Need correction to Diagram - Some Pin connections are incorrect.

### ISSUE THREAD

**Issue by space1649** [beneater/eeprom-programmer#2]
D2 D3 and D4 should be connected to Pin 14, Pin(s) 11, Pin(s) 12 respectfully.
Here is a corrected diagram.
![ben s diagram correction](https://cloud.githubusercontent.com/assets/26715816/24964996/62ec4d66-1f68-11e7-82a9-f06699da851d.png)

**Comment by martinKindall** [comment]
Thanks for pointing this out, I used this correction and my circuit worked!
I used a 28C16, I did some modificacion to match the pins from A0 to A10 (28C16 doesnt have A11-A14) and WE, OE and CS.

**Comment by ChrisOMills** [comment]
Thanks! this helped me out a lot!
